spring:
    datasource:
        url: jdbc:mysql://localhost:3306/training
        username: springstudent
        password: springstudent
        driver-class-name: org.mariadb.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MariaDB103Dialect
                show_sql: true
                use_sql_comments: true
                format_sql: true
                type: trace
        show-sql: true
logging:
    level:
        org:
            hiberate: TRACE

